import { FileMinus2, Printer } from "lucide-react";
import type { AnswerView } from "@/contracts";
import { Button, EmptyState } from "@/components/ui/primitives";
import { fmtUsd } from "@/lib/format";
import { isFixtureId } from "@/data/fixtures";

/** Formal SAR document. Rendered only when the answer says `sar.file: true`. */
export function SarTab({ answer }: { answer: AnswerView }) {
  const sar = answer.sar;
  if (!sar.file) {
    return (
      <EmptyState icon={<FileMinus2 className="h-8 w-8" />} title="No suspicious activity report was filed for this case">
        <p className="mt-1">
          <span className="text-zinc-500">Reason recorded by the backend: </span>
          <span className="text-zinc-200">{sar.reason || "none supplied"}</span>
        </p>
      </EmptyState>
    );
  }
  const [first, last] = sar.activity_dates;
  const paragraphs = sar.narrative.split(/\n{2,}/).filter(Boolean);
  const demo = isFixtureId(answer.case_id);
  return (
    <div className="space-y-3">
      <div className="no-print flex flex-wrap items-center justify-between gap-2">
        <p className="text-[13px] text-zinc-400">Formatted for reading and printing. Choose &quot;Save as PDF&quot; in the print dialog to export.</p>
        <Button onClick={() => window.print()}>
          <Printer className="h-4 w-4" aria-hidden /> Print / save PDF
        </Button>
      </div>
      <article className="print-area mx-auto max-w-[820px] rounded-sm bg-[#fbfaf7] px-10 py-10 font-serif text-[#1b1b1b] shadow-2xl ring-1 ring-black/10" aria-label="Suspicious activity report">
        {demo && (
          <p className="mb-5 border-2 border-dashed border-amber-600 px-3 py-1.5 text-center font-sans text-[12px] font-bold uppercase tracking-widest text-amber-800">
            Demo fixture — not a real filing
          </p>
        )}
        <header className="border-b-2 border-[#1b1b1b] pb-4">
          <p className="font-sans text-[11px] font-semibold uppercase tracking-[0.2em] text-[#6b6b6b]">Suspicious Activity Report · Draft for filing</p>
          <h2 className="mt-1 text-[26px] font-bold leading-tight">Case {answer.case_id}</h2>
          <p className="mt-1 font-sans text-[12px] text-[#555]">Graph case record: {answer.case.graph_case_id || "not written"}</p>
        </header>
        <dl className="mt-5 grid grid-cols-1 gap-x-8 gap-y-4 font-sans text-[13px] sm:grid-cols-3">
          <div>
            <dt className="text-[10.5px] font-semibold uppercase tracking-widest text-[#6b6b6b]">Total amount</dt>
            <dd className="mt-0.5 font-mono text-[18px] font-semibold">{fmtUsd(sar.total_amount_usd)}</dd>
          </div>
          <div>
            <dt className="text-[10.5px] font-semibold uppercase tracking-widest text-[#6b6b6b]">Activity date range</dt>
            <dd className="mt-0.5 font-mono text-[15px]">
              {first ?? "—"} <span className="text-[#888]">→</span> {last ?? "—"}
            </dd>
          </div>
          <div>
            <dt className="text-[10.5px] font-semibold uppercase tracking-widest text-[#6b6b6b]">Pattern</dt>
            <dd className="mt-0.5 font-mono text-[14px]" style={{ overflowWrap: "anywhere" }}>{answer.case.pattern}</dd>
          </div>
          <div className="sm:col-span-3">
            <dt className="text-[10.5px] font-semibold uppercase tracking-widest text-[#6b6b6b]">Subjects</dt>
            <dd className="mt-1 flex flex-wrap gap-1.5">
              {sar.subjects.map((s) => (
                <span key={s} className="rounded border border-[#bbb] bg-white px-1.5 py-0.5 font-mono text-[12px]" style={{ overflowWrap: "anywhere" }}>
                  {s}
                </span>
              ))}
            </dd>
          </div>
          <div className="sm:col-span-3">
            <dt className="text-[10.5px] font-semibold uppercase tracking-widest text-[#6b6b6b]">Filing reason</dt>
            <dd className="mt-0.5 text-[13.5px] leading-6">{sar.reason}</dd>
          </div>
        </dl>
        <section className="mt-6 border-t border-[#ccc] pt-5">
          <h3 className="font-sans text-[10.5px] font-semibold uppercase tracking-widest text-[#6b6b6b]">Narrative</h3>
          <div className="mt-2 space-y-3 text-[15.5px] leading-[1.75]" style={{ overflowWrap: "anywhere" }}>
            {paragraphs.map((p, i) => (
              <p key={i}>{p}</p>
            ))}
          </div>
        </section>
        <footer className="mt-8 border-t border-[#ccc] pt-3 font-sans text-[11px] text-[#777]">
          Generated by the FraudGraph Investigator backend and displayed verbatim from the answer file. Customer or analyst responses referenced here were simulated during the investigation.
        </footer>
      </article>
    </div>
  );
}
