/**
 * Fixture-mode vocabulary. The fixture JSON itself lives in `ui/fixtures/`
 * (generated by scripts/generate-fixtures.mjs) and reaches the browser only via
 * `npm run sync-data -- --fixtures`.
 */
export const DEMO_BANNER =
  "DEMO DATA — backend results have not been synchronized. Values on this site are interface fixtures, not investigation outcomes.";

export const FIXTURE_ID_PREFIX = "DEMO-";

export const isFixtureId = (id: string) => id.startsWith(FIXTURE_ID_PREFIX);

/** What each interface fixture is meant to exercise (shown in fixture mode only). */
export const FIXTURE_PURPOSE: Record<string, string> = {
  "DEMO-001": "Fraud · evidence request · changed actions · filed SAR · shared-device graph",
  "DEMO-002": "Legitimate · zero exposure · no SAR · no evidence request",
  "DEMO-003": "Uncertain · analyst escalation · trace deliberately missing",
  "DEMO-004": "Undocumented pattern · graph write failed · unknown trace vocabulary",
  "DEMO-005": "Card testing · ~230-node graph · read-back failed",
  "DEMO-006": "Valid answer with a deliberately malformed trace",
};
